### ISSUE TITLE
Stuck at Google meet homescreen

### ISSUE THREAD

**Issue by magbanum** [Titan1911/Google-Meet-Attendance-using-Python#4]
After running the code. It asks for email Id, Password, and meet link.
After that new home window is opened and automatically login to google account.
Then google meet's home screen is opened and does not move further.

**Comment by Titan1911** [comment]
The issue you are facing is I think because you might be logging in with an organization mail ID. Try logging in with a local gmail ID, might help.

**Comment by magbanum** [comment]
Tried but getting another error
