### ISSUE TITLE
Code Work until...

### ISSUE THREAD

**Issue by SlamberGamer** [Titan1911/Google-Meet-Attendance-using-Python#6]
Hi your code works until counting how many people in the class but doest pull and save any name in the google attendance sheet

**Comment by Titan1911** [comment]
Hey, did u follow all the steps in the README.md? It might be that you didn't close the sheet while running the program. Just check it once more.

**Comment by SlamberGamer** [comment]
Hi i did close the sheet.. its says its completed and shows number of participant but never updated in the excel the list of the name.. i will test it again tomorrow..  and thank you for you feedback..
